//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbAnswer()
        {
            this.tbUserAnswers = new HashSet<tbUserAnswer>();
        }
    
        public int AnsId { get; set; }
        public Nullable<int> QuestId { get; set; }
        public string Text { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
    
        public virtual tbQuestion tbQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserAnswer> tbUserAnswers { get; set; }
    }
}
