//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUser()
        {
            this.tbUserAnswers = new HashSet<tbUserAnswer>();
        }
    
        public int U_Id { get; set; }
        [Display(Name = "User Name")]
        [Required(ErrorMessage = "*")]
        public string U_Name { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "*")]
        public string U_Password { get; set; }
        public Nullable<int> U_Score { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserAnswer> tbUserAnswers { get; set; }
    }
}
