//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUserAnswer
    {
        public int Id { get; set; }
        public Nullable<int> Ans_Id { get; set; }
        public Nullable<int> QuestId { get; set; }
        public Nullable<int> U_Id { get; set; }
    
        public virtual tbAnswer tbAnswer { get; set; }
        public virtual tbQuestion tbQuestion { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
